config/routes.rb
Rails.application.routes.draw do

  resources :stock_news
  default_url_options :host => "localhost:3000"

 resources :friends 
 resources :friendships, only: [:create, :destroy]
 resources :users, only: [:show]
 resources :dashboard, only: [:index]
 resources :user_stocks, only: [:create, :destroy]
 devise_for :users, path: 'auth', controllers: { sign_in: 'login',
 sign_out: 'logout',
   confirmations: 'confirmations'
 }

  root 'dashboard#index'
  get 'index', to: 'dashboard#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  get 'my_friends', to: 'users#my_friends'
  # post 'friend', to: 'users#friends'
  #get 'friends_portfolio', to: 'user_friends#friend_portfolio' 

  get 'my_friends/:id/portfolio', to: 'users#friend_portfolio', as: 'friend_portfolio'
 
  

  # Route structure : 
  # verb (get | post | put | patch | delete)
  # name of route : 
  #   |  / (absolute path), no / (relative path)
  #   |  names can be composed name : my-friends
  #   |  or can have params : friends/:id  :id is accessible im params[:id]
  # to : controllerName#method
  # as : pathName (alias)

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_list.html.erb
<div class="results-table">
  <div class="row">
    <div class="col-10">
      <div class="search">
        <%= form_tag search_friend_path, remote: true, method: :get do %>
          <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
              <%= text_field_tag :friend, params[:friend], placeholder: "Enter a Friend's Email", autofocus: true, class:"form-control me-2" %>
            </div>
            <div class="col-sm-3 no-left-padding">
              <%= button_tag type: :submit, class:"btn btn-success" do %>
                <%= 'Search' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div id="results">
      </div>
      <table class="table table-dark table-hover">
        <thead>
          <tr>
            <th scope="col">Email</th>
            <th scope="col">Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @friends.each do |friend| %>
            <tr>
              <th scope="row"><%= friend.email %></th>
              <td><%= friend.first_name %></td>
              <td><%= friend.last_name %></td>
              <td><%= link_to "View Profile", user_path(friend),
      class:"btn btn-sm btn-success" %>
              <td><%= link_to 'Stop Following', friendship_path(friend), method: :delete, data: {confirm: 'Are you Sure?'},
            class: 'btn btn-xs btn-warning'  %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/friends/_result.htm.erb
<div class='results-block'>

</div>

<% if @friend %>
<div class="card card-header results-block">
    <strong>Name: </strong> <%= @friend.full_name %>
    <strong>Email: </strong> <%= @friend.email %>
  
   
    <% if current_user.can_track_friend?(@friend.email) %>
    <%= link_to 'Add to Friends List', my_friends_path(user: current_user, email: @friend.email), 
                                    class: "btn btn-xs btn-success", method: :post %>

                                     <% else %>
    <span class="badge badge-secondary">
    You are already tracking this friend
    
    <% if current_user.friend_already_tracked?(@friend.email) %> 
    this friend
<% end %>
</span>
<% end %>
</div>
<% end %>

app/views/friends/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<% if @friends %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Name: </strong> <%= friend.full_name %></td>
            <td><strong>Email: </strong> <%= friend.email %></td>
            <td><strong>Actions: </strong> <%= link_to "View Profile", user_path(friend),
      class:"btn btn-sm btn-success" %>
            <% if current_user.not_friends_with?(friend.id) %>
                <%= link_to 'Follow Friend ?', friendships_path(friend: friend), 
                                    class: "btn btn-sm btn-success", method: :post %>
            <% else %>
                <span class="badge badge-secondary">
                You are friends
                </span>
            <% end  %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/friends/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'friends/result.html'%>'