config/routes.rb
Rails.application.routes.draw do

  resources :stock_news
  default_url_options :host => "localhost:3000"

 resources :friends 
 resources :friendships, only: [:create, :destroy]
 resources :users, only: [:show]
 resources :dashboard, only: [:index]
 resources :user_stocks, only: [:create, :destroy]
 devise_for :users, path: 'auth', controllers: { sign_in: 'login',
 sign_out: 'logout',
   confirmations: 'confirmations'
 }

  root 'dashboard#index'
  get 'index', to: 'dashboard#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  get 'my_friends', to: 'users#my_friends'
  # post 'friend', to: 'users#friends'
  #get 'friends_portfolio', to: 'user_friends#friend_portfolio' 

  get 'my_friends/:id/portfolio', to: 'users#friend_portfolio', as: 'friend_portfolio'
 
  

  # Route structure : 
  # verb (get | post | put | patch | delete)
  # name of route : 
  #   |  / (absolute path), no / (relative path)
  #   |  names can be composed name : my-friends
  #   |  or can have params : friends/:id  :id is accessible im params[:id]
  # to : controllerName#method
  # as : pathName (alias)

end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
                                  endpoint: 'https://sandbox.iexapis.com/v1')
    begin
        new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
      end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
 end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  
  
  
  def search

    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
            flash.now[:alert] = 'Please enter valid symbol to search'
            format.js { render partial: 'users/result' }
        end 
      end
    else
        respond_to do |format|
            flash.now[:alert] = 'Please enter a symbol to search'
            format.js { render partial: 'users/result' }
        end
    end
  end
end

app/views/stocks/_list.html.erb
<div class="results-table">
  <h1>Portfolio</h1>
  <div class="row">
    <div class="col-10">
      <div class="search">
        <%= form_tag search_stock_path, remote: true, method: :get do %>
          <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
              <%= text_field_tag :stock, params[:stock], placeholder: "Stock Ticker Symbol", autofocus: true, class:"form-control me-2" %>
            </div>
            <div class="col-sm-3 no-left-padding">
              <%= button_tag type: :submit, class:"btn btn-success" do %>
                <%= 'Search' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div id="results">
      </div>
      <table class="table table-dark table-hover">
        <thead>
          <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tracked_stocks.each do |stock| %>
            <tr>
              <th scope="row"><%= stock.ticker %></th>
              <td><%= stock.name %></td>
              <td><%= stock.last_price %></td>

          <td> <% if current_user.can_track_stock?(stock.ticker) %>

             <%= link_to 'Add to Portfolio', user_stocks_path(user: current_user, ticker: stock.ticker), 
                                    class: "btn btn-xs btn-success", method: :post %> 
              <% elsif current_user.id != @user.id%>
                <span class="badge badge-secondary">
                  You are already tracking
                  <% if !current_user.under_stock_limit? %>
                    10 stocks 
                    <%end%>
                    </span>
                  <% end %>

                 <% if current_user.id == @user.id %>

                      <td> <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you Sure?'},
            class: 'btn btn-xs btn-warning'  %>
                    <%end%>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>