config/routes.rb
Rails.application.routes.draw do

  resources :stock_news
  default_url_options :host => "localhost:3000"

 resources :friends 
 resources :friendships, only: [:create, :destroy]
 resources :users, only: [:show]
 resources :dashboard, only: [:index]
 resources :user_stocks, only: [:create, :destroy]
 devise_for :users, path: 'auth', controllers: { sign_in: 'login',
 sign_out: 'logout',
   confirmations: 'confirmations'
 }

  root 'dashboard#index'
  get 'index', to: 'dashboard#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  get 'my_friends', to: 'users#my_friends'
  # post 'friend', to: 'users#friends'
  #get 'friends_portfolio', to: 'user_friends#friend_portfolio' 

  get 'my_friends/:id/portfolio', to: 'users#friend_portfolio', as: 'friend_portfolio'
 
  

  # Route structure : 
  # verb (get | post | put | patch | delete)
  # name of route : 
  #   |  / (absolute path), no / (relative path)
  #   |  names can be composed name : my-friends
  #   |  or can have params : friends/:id  :id is accessible im params[:id]
  # to : controllerName#method
  # as : pathName (alias)

end

app/views/user_friends/index.html.erb
<div id="results">
<h1>Friends</h1>
  <div class="row">
    <div class="col-9">
      <table class="table table-dark table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Portfolio</th>
            <th scope="col">Add</th> 
            <th scope="col">Remove</th>
          </tr>
        </thead>
        <tbody>
         <% @tracked_friends.each do |friend| %>
          <tr>
            <th scope="row"><%= friend.full_name %></th>
            <td><%= friend.email %></td>
            <td><%= link_to "Portfolio", friend_portfolio_path(friend.id) %></td>
            <td><%= link_to 'Remove', user_friends_url(friend), method: :delete, data: {confirm: 'Are you Sure?'},
            class: 'btn btn-xs btn-warning'  %></td>
          </tr>
          <% end %>
    
        </tbody>
      </tbody>
</table>

    </div>      